### ISSUE TITLE
Setting tokenOwnerClass

### ISSUE THREAD

**Issue by beardybanana** [colymba/silverstripe-restfulapi#103]
I am having trouble setting the tokenOwnerClass

I have added TokenAuthExtension to the 'Project' dataobject and this works - I can see that these DB fields are created on Project.

However, the tokenOwnerClass in my YML file is not recognized and it defaults back to Member.

Any tips on this?

config:

Project:
  extensions:
    - Colymba\RESTfulAPI\Extensions\TokenAuthExtension
TokenAuthenticator:
    tokenOwnerClass: 'Project'

**Comment by colymba** [comment]
Have you tried with the full namespace?

**Comment by beardybanana** [comment]
Hey there! Yes I did, and it worked, thanks so much!
