### ISSUE TITLE
default limit?

### ISSUE THREAD

**Issue by nimeso** [colymba/silverstripe-restfulapi#85]
Is there a default limit on records? 
eg: http://mysite/api/Point only returns like 200 records but http://mysite/api/Point?__limit=1000 will return them all.

**Comment by colymba** [comment]
Yes there is a default which should be 100:
https://github.com/colymba/silverstripe-restfulapi/blob/master/doc/DefaultQueryHandler.md

You can have it set via the config for all requests or via query Param like you found.
