### ISSUE TITLE
Access to token on dataobjects

### ISSUE THREAD

**Issue by rodwin** [colymba/silverstripe-restfulapi#86]
Thank you for this module.

Is there a way to access the token inside the onAfterSerialize or onBeforeDeserialize or anywhere in the dataobject?

I need to get some user details to be included on the response and I think using Member::currentUserID() is not ideal since its using session.

Thanks

**Comment by colymba** [comment]
Hey! if the token auth extension is on the Member class, the authenticator calls this `Session::set("loggedInAs", $tokenOwner->ID);` when a `Member` is authenticated, so with `Session::get("loggedInAs")` you get the `Member` ID and can do a DB call to get the DO. If `Member::currentUserID()` works, I would use it.

**Comment by rodwin** [comment]
Thanks. Closing this now
