### ISSUE TITLE
Lost password existing account disclosure

### ISSUE THREAD

**Issue by UndefinedOffset** [colymba/silverstripe-restfulapi#88]
Should the ``api/auth/lostPassword?email=***`` endpoint return anything other than a generic response i.e ``{"email":true}`` rather than what it currently does which is two different responses one if the account exists and one if it does not? It would probably be better for security if it returned a generic response much like ``/Security/lostpassword`` does.

**Comment by UndefinedOffset** [comment]
I have a proposed fix [in the Webbuilders Group fork](https://github.com/webbuilders-group/silverstripe-restfulapi/commit/26e05d2d426031729a21c5d9f422128aad7616af) if you agree I'll submit a pull request accordingly for you to merge.

**Comment by colymba** [comment]
Thanks @UndefinedOffset, sounds good to me! One suggestion, should we change `"email"` in the response to `done` or something else generic?

**Comment by UndefinedOffset** [comment]
Ya I like that idea, I've switched it to done and will open a pull shortly

**Comment by colymba** [comment]
thanks @UndefinedOffset !
