### ISSUE TITLE
model_permission_check instanceof Member not namespaced

### ISSUE THREAD

**Issue by lukeskelding** [colymba/silverstripe-restfulapi#97]
There is a check on line 548 of RESTfulAPI.php:

https://github.com/colymba/silverstripe-restfulapi/blob/b24b7eb0c139a83a9c5cc9194a780e8882914c44/src/RESTfulAPI.php#L548

This checks the authenticator owner is a member instance. This reference to Member hasn't been namespaced for SS4 (SilverStripe\Security\Member) so its never true meaning the model level checks fail.

**Comment by colymba** [comment]
should be fixed by #99
